package com.cccclab.expertsystemclient.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ExpertSystemClientLoginDesign extends VerticalLayout {
	protected FormLayout formLayout;
	protected TextField tf_loginusername;
	protected PasswordField pf_login_password;
	protected Button btn_login;

	public ExpertSystemClientLoginDesign() {
		Design.read(this);
	}
}
